name: Eleventy Build
on: [push]

# Conditional environmental if's      
env:
  UPDATE_NPM: false # false = deploy eleventy , true = update npm

jobs:
  build_deploy_eleventy:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.UPDATE_NPM }}
      - name: checkout
        if: env.UPDATE_NPM != 'true'
        uses: actions/checkout@v2
      - name: Build 11ty
        if: env.UPDATE_NPM != 'true'
        uses: woodcock3/actions-eleventy@master
        with:
          args: --output _dist --pathprefix /11up/
          install_dependencies: true
          build_script: build
      - name: Deploy
        if: env.UPDATE_NPM != 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_dist 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}


  # Update NPM if env.UPDATE_NPM = true
  npm-update:
    name: npm update
    runs-on: ubuntu-latest
    steps:
      # condition - if UPDATE_NPM = true
      - run: echo '${{ env.UPDATE_NPM }}'
      - name: Checkout
        if: env.UPDATE_NPM == 'true'
        uses: actions/checkout@v2
      - name: Setup Node
        if: env.UPDATE_NPM == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm init -y
        if: env.UPDATE_NPM == 'true'
      - run: npm install
        if: env.UPDATE_NPM == 'true'
      # - run: npm uninstall
      # - run: npm update # update packages
      - name: pull request on npm update
        if: env.UPDATE_NPM == 'true'
        uses: woodcock3/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            - Dependency updates
  
            Auto-generated by [create-pull-request][1]
  
            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
